package Excepetion_handaling;

public class B {
public static void main(String[] args) {
	int a=10;
	int b=0;
	try {
		int c=a/b;
		
	}
	catch(ArithmeticException monkey) {
		System.out.println("idiat iner validete denomeneter");
		System.out.println("exception is handaled");
	}
	
}
}
